version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "client-web/package.json" }}
            - v1-dependencies-
      - run:
          name: Install npms
          command: |
            npm install; npm rebuild node-sass
      - run:
          name: Install npms(Client)
          command: |
            cd client-web; npm install; npm rebuild node-sass
      - run:
          name: Install dependencies
          command: sudo apt-get install -y python3-pip; sudo pip3 install awscli
      - save_cache:
          paths:
            - node_modules
            - client-web/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "client-web/package.json" }}
      - run:
          name: Build Vue.js module
          command: cd client-web; npm run build
      - run:
          name: Running tslint
          command: npm run tslint-check
      - run:
          name: Running lint
          command: npm run lint
      - run:
          name: Running tests
          command: npm run test
      - store_artifacts:
          path: ~/repo/coverage
          destination: coverage
      - run:
          name: Push application Docker image
          command: |
            if [[ ${CIRCLE_BRANCH} =~ feature ]]; then
              echo "No push branch: ${CIRCLE_BRANCH}"
              exit 0
            else
              echo "export IMAGE_TAG=${CIRCLE_BUILD_NUM}" >> $BASH_ENV
              source $BASH_ENV
            fi
            echo "export IMAGE_NAME=${REPOSITORY_NAME}:${IMAGE_TAG}" >> $BASH_ENV
            source $BASH_ENV
            echo "IMAGE_TAG: ${IMAGE_TAG} / IMAGE_NAME: ${IMAGE_NAME}"
            docker build -t ${IMAGE_NAME} .
            $(aws ecr get-login --no-include-email)
            docker tag ${IMAGE_NAME} ${ECR_ENDPOINT}/${IMAGE_NAME}
            if [ -n "${CIRCLE_TAG}" ]; then
              docker tag ${IMAGE_NAME} ${ECR_ENDPOINT}/${REPOSITORY_NAME}:${CIRCLE_TAG}
            fi
            docker push ${ECR_ENDPOINT}/${IMAGE_NAME}
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop
                - /^feature.*/
  release-build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
